var _____WB$wombat$assign$function_____ = function(name) {return (self._wb_wombat && self._wb_wombat.local_init && self._wb_wombat.local_init(name)) || self[name]; };
if (!self.__WB_pmw) { self.__WB_pmw = function(obj) { this.__WB_source = obj; return this; } }
{
  let window = _____WB$wombat$assign$function_____("window");
  let self = _____WB$wombat$assign$function_____("self");
  let document = _____WB$wombat$assign$function_____("document");
  let location = _____WB$wombat$assign$function_____("location");
  let top = _____WB$wombat$assign$function_____("top");
  let parent = _____WB$wombat$assign$function_____("parent");
  let frames = _____WB$wombat$assign$function_____("frames");
  let opener = _____WB$wombat$assign$function_____("opener");

(function(){var g=true,i=null,j=false,aa=(new Date).getTime(),k=function(a){var b=(new Date).getTime()-aa;b="&dtd="+(b<1E3?b:"M");return a+b};var l=this,ba=function(a,b,c){a=a.split(".");c=c||l;!(a[0]in c)&&c.execScript&&c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)if(!a.length&&b!==undefined)c[d]=b;else c=c[d]?c[d]:(c[d]={})},m=function(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array||!(a instanceof Object)&&Object.prototype.toString.call(a)=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";
if(!(a instanceof Object)&&(Object.prototype.toString.call(a)=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call")))return"function"}else return"null";else if(b=="function"&&typeof a.call=="undefined")return"object";return b},o=function(a){return m(a)=="array"},ca=function(a){var b=m(a);return b=="array"||b=="object"&&typeof a.length=="number"},p=function(a){return typeof a=="string"},da=function(a){a=m(a);return a=="object"||
a=="array"||a=="function"},ea=function(a){var b=m(a);if(b=="object"||b=="array"){if(a.clone)return a.clone.call(a);b=b=="array"?[]:{};for(var c in a)b[c]=ea(a[c]);return b}return a},fa=function(a,b){var c=b||l;if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(c,e)}}else return function(){return a.apply(c,arguments)}},ga=Date.now||function(){return+new Date},q=function(a,
b,c){ba(a,b,c)};var r=Array.prototype,ha=r.forEach?function(a,b,c){r.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=p(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},ia=function(){return r.concat.apply(r,arguments)},ja=function(a){if(o(a))return ia(a);else{for(var b=[],c=0,d=a.length;c<d;c++)b[c]=a[c];return b}};var s=function(a,b){this.width=a;this.height=b};s.prototype.clone=function(){return new s(this.width,this.height)};s.prototype.toString=function(){return"("+this.width+" x "+this.height+")"};s.prototype.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};s.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
s.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};s.prototype.scale=function(a){this.width*=a;this.height*=a;return this};var ka=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};var qa=function(a,b){if(b)return a.replace(la,"&amp;").replace(ma,"&lt;").replace(na,"&gt;").replace(oa,"&quot;");else{if(!pa.test(a))return a;if(a.indexOf("&")!=-1)a=a.replace(la,"&amp;");if(a.indexOf("<")!=-1)a=a.replace(ma,"&lt;");if(a.indexOf(">")!=-1)a=a.replace(na,"&gt;");if(a.indexOf('"')!=-1)a=a.replace(oa,"&quot;");return a}},la=/&/g,ma=/</g,na=/>/g,oa=/\"/g,pa=/[&<>\"]/,ta=function(a){if(a.indexOf("&")!=-1)return"document"in l&&a.indexOf("<")==-1?ra(a):sa(a);return a},ra=function(a){var b=
l.document.createElement("a");b.innerHTML=a;b.normalize&&b.normalize();a=b.firstChild.nodeValue;b.innerHTML="";return a},sa=function(a){return a.replace(/&([^;]+);/g,function(b,c){switch(c){case "amp":return"&";case "lt":return"<";case "gt":return">";case "quot":return'"';default:if(c.charAt(0)=="#"){c=Number("0"+c.substr(1));if(!isNaN(c))return String.fromCharCode(c)}return b}})},ua=function(a,b){for(var c=b.length,d=0;d<c;d++){var e=c==1?b:b.charAt(d);if(a.charAt(0)==e&&a.charAt(a.length-1)==e)return a.substring(1,
a.length-1)}return a},va=function(a,b){var c=0;a=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split(".");b=String(b).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split(".");for(var d=Math.max(a.length,b.length),e=0;c==0&&e<d;e++){var f=a[e]||"",h=b[e]||"",n=new RegExp("(\\d*)(\\D*)","g"),x=new RegExp("(\\d*)(\\D*)","g");do{var F=n.exec(f)||["","",""],G=x.exec(h)||["","",""];if(F[0].length==0&&G[0].length==0)break;c=F[1].length==0?0:parseInt(F[1],10);var db=G[1].length==0?0:parseInt(G[1],10);c=t(c,db)||
t(F[2].length==0,G[2].length==0)||t(F[2],G[2])}while(c==0)}return c},t=function(a,b){if(a<b)return-1;else if(a>b)return 1;return 0};ga();var u,v,w,y,z,wa,xa,ya,za,Aa=function(){return l.navigator?l.navigator.userAgent:i},A=function(){return l.navigator},Ba=function(){z=y=w=v=u=j;var a;if(a=Aa()){var b=A();u=a.indexOf("Opera")==0;v=!u&&a.indexOf("MSIE")!=-1;y=(w=!u&&a.indexOf("WebKit")!=-1)&&a.indexOf("Mobile")!=-1;z=!u&&!w&&b.product=="Gecko"}};Ba();
var B=u,C=v,Ca=z,Da=w,Ea=y,Fa=function(){var a=A();return a&&a.platform||""},D=Fa(),Ga=function(){wa=D.indexOf("Mac")!=-1;xa=D.indexOf("Win")!=-1;ya=D.indexOf("Linux")!=-1;za=!!A()&&(A().appVersion||"").indexOf("X11")!=-1};Ga();var Ha=ya,Ia=function(){var a="",b;if(B&&l.opera){a=l.opera.version;a=typeof a=="function"?a():a}else{if(Ca)b=/rv\:([^\);]+)(\)|;)/;else if(C)b=/MSIE\s+([^\);]+)(\)|;)/;else if(Da)b=/WebKit\/(\S+)/;if(b)a=(a=b.exec(Aa()))?a[1]:""}return a},Ja=Ia(),E={};var Ka=function(a){return p(a)?document.getElementById(a):a},H=Ka,Ma=function(a,b){ka(b,function(c,d){if(d=="style")a.style.cssText=c;else if(d=="class")a.className=c;else if(d=="for")a.htmlFor=c;else if(d in La)a.setAttribute(La[d],c);else a[d]=c})},La={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",rowspan:"rowSpan",valign:"vAlign",height:"height",width:"width",usemap:"useMap",frameborder:"frameBorder",type:"type"},Na=function(a){var b=a.document;if(Da&&!(E["500"]||(E["500"]=
va(Ja,"500")>=0))&&!Ea){if(typeof a.innerHeight=="undefined")a=window;b=a.innerHeight;var c=a.document.documentElement.scrollHeight;if(a==a.top)if(c<b)b-=15;return new s(a.innerWidth,b)}a=b.compatMode=="CSS1Compat"&&(!B||B&&(E["9.50"]||(E["9.50"]=va(Ja,"9.50")>=0)))?b.documentElement:b.body;return new s(a.clientWidth,a.clientHeight)},Pa=function(){return Oa(document,arguments)},Oa=function(a,b){var c=b[0],d=b[1];if(C&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',qa(d.name),'"');if(d.type){c.push(' type="',
qa(d.type),'"');d=ea(d);delete d.type}c.push(">");c=c.join("")}var e=a.createElement(c);if(d)if(p(d))e.className=d;else Ma(e,d);if(b.length>2){d=function(h){if(h)e.appendChild(p(h)?a.createTextNode(h):h)};for(c=2;c<b.length;c++){var f=b[c];ca(f)&&!(da(f)&&f.nodeType>0)?ha(Qa(f)?ja(f):f,d):d(f)}}return e},Ra=function(a,b){a.appendChild(b)},Qa=function(a){if(a&&typeof a.length=="number")if(da(a))return typeof a.item=="function"||typeof a.item=="string";else if(m(a)=="function")return typeof a.item==
"function";return j};function I(a,b){a=parseFloat(a);return isNaN(a)||a>1||a<0?b:a}function J(a,b){if(a=="true")return g;if(a=="false")return j;return b};var Sa=document,Ta=J("false",j),Ua=J("false",j),Va=J("false",j),K=window;var Wa="pagead2.googlesyndication.com",Xa="googleads.g.doubleclick.net",Ya="googleads2.g.doubleclick.net",Za=Wa,$a=Xa,ab=Ya,bb=Wa;var L=function(a,b){for(var c in a)Object.prototype.hasOwnProperty.call(a,c)&&b.call(i,a[c],c,a)},cb=function(a){if(arguments.length<2)return a.length;for(var b=1,c=arguments.length;b<c;++b)a.push(arguments[b]);return a.length};function M(a){return typeof encodeURIComponent=="function"?encodeURIComponent(a):escape(a)}
function eb(a,b,c){var d=document.createElement("script");d.type="text/javascript";if(b)d.onload=b;if(c)d.id=c;d.src=a;var e=document.getElementsByTagName("head")[0];if(!e)return j;window.setTimeout(function(){e.appendChild(d)},0);return g}function fb(a,b){a.google_image_requests||(a.google_image_requests=[]);var c=new Image;c.src=b;a.google_image_requests.push(c)}function gb(a){if(a in N)return N[a];return N[a]=navigator.userAgent.toLowerCase().indexOf(a)!=-1}var N={};
function hb(){if(navigator.plugins&&navigator.mimeTypes.length){var a=navigator.plugins["Shockwave Flash"];if(a&&a.description)return a.description.replace(/([a-zA-Z]|\s)+/,"").replace(/(\s)+r/,".")}else if(navigator.userAgent&&navigator.userAgent.indexOf("Windows CE")>=0){a=3;for(var b=1;b;)try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+(a+1));a++}catch(c){b=i}return a.toString()}else if(gb("msie")&&!window.opera){b=i;try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7")}catch(d){a=
0;try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");a=6;b.AllowScriptAccess="always"}catch(e){if(a==6)return a.toString()}try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(f){}}if(b){a=b.GetVariable("$version").split(" ")[1];return a.replace(/,/g,".")}}return"0"}function O(a){var b=a.google_ad_format;if(b)return b.indexOf("_0ads")>0;return a.google_ad_output!="html"&&a.google_num_radlinks>0}function P(a){return!!a&&a.indexOf("_sdo")!=-1}
function Q(a,b){var c=Math.random();if(c<b){b=Math.floor(c/b*a.length);return a[b]}return""}
var ib=function(a){a.u_tz=-(new Date).getTimezoneOffset();a.u_his=window.history.length;a.u_java=navigator.javaEnabled();if(window.screen){a.u_h=window.screen.height;a.u_w=window.screen.width;a.u_ah=window.screen.availHeight;a.u_aw=window.screen.availWidth;a.u_cd=window.screen.colorDepth}if(navigator.plugins)a.u_nplug=navigator.plugins.length;if(navigator.mimeTypes)a.u_nmime=navigator.mimeTypes.length},jb=function(a){var b=K;if(a&&b.top!=b)b=b.top;try{return b.document&&!b.document.body?new s(-1,
-1):Na(b||window)}catch(c){return new s(-12245933,-12245933)}},kb=function(a,b){var c=a.length;if(c==0)return 0;b=b||305419896;for(var d=0;d<c;d++){var e=a.charCodeAt(d);b^=(b<<5)+(b>>2)+e&4294967295}return b},lb=function(a){if(a==a.top)return 0;var b=[];b.push(document.URL);a.name&&b.push(a.name);a=g;a=jb(!a);b.push(a.width.toString());b.push(a.height.toString());b=kb(b.join(""));return b>0?b:4294967296+b};var mb={google_ad_channel:"channel",google_ad_host:"host",google_ad_host_channel:"h_ch",google_ad_host_tier_id:"ht_id",google_ad_section:"region",google_ad_type:"ad_type",google_adtest:"adtest",google_allow_expandable_ads:"ea",google_alternate_ad_url:"alternate_ad_url",google_alternate_color:"alt_color",google_bid:"bid",google_city:"gcs",google_color_bg:"color_bg",google_color_border:"color_border",google_color_line:"color_line",google_color_link:"color_link",google_color_text:"color_text",google_color_url:"color_url",
google_contents:"contents",google_country:"gl",google_cust_age:"cust_age",google_cust_ch:"cust_ch",google_cust_gender:"cust_gender",google_cust_id:"cust_id",google_cust_interests:"cust_interests",google_cust_job:"cust_job",google_cust_l:"cust_l",google_cust_lh:"cust_lh",google_cust_u_url:"cust_u_url",google_disable_video_autoplay:"disable_video_autoplay",google_ed:"ed",google_encoding:"oe",google_feedback:"feedback_link",google_flash_version:"flash",google_font_face:"f",google_font_size:"fs",google_hints:"hints",
google_kw:"kw",google_kw_type:"kw_type",google_language:"hl",google_page_url:"url",google_region:"gr",google_reuse_colors:"reuse_colors",google_safe:"adsafe",google_tag_info:"gut",google_targeting:"targeting",google_ui_features:"ui",google_ui_version:"uiv",google_video_doc_id:"video_doc_id",google_video_product_type:"video_product_type"},nb={google_ad_client:"client",google_ad_format:"format",google_ad_output:"output",google_ad_callback:"callback",google_ad_height:"h",google_ad_override:"google_ad_override",
google_ad_slot:"slotname",google_ad_width:"w",google_ctr_threshold:"ctr_t",google_image_size:"image_size",google_last_modified_time:"lmt",google_max_num_ads:"num_ads",google_max_radlink_len:"max_radlink_len",google_num_radlinks:"num_radlinks",google_num_radlinks_per_unit:"num_radlinks_per_unit",google_only_ads_with_video:"only_ads_with_video",google_rl_dest_url:"rl_dest_url",google_rl_filtering:"rl_filtering",google_rl_mode:"rl_mode",google_rt:"rt",google_skip:"skip"},ob={google_only_pyv_ads:"pyv",
google_with_pyv_ads:"withpyv"};function pb(a,b){try{return a.top.document.URL==b.URL}catch(c){}return j}function qb(a,b,c,d){c=c||a.google_ad_width;d=d||a.google_ad_height;if(pb(a,b))return j;var e=b.documentElement;if(c&&d){var f=1,h=1;if(a.innerHeight){f=a.innerWidth;h=a.innerHeight}else if(e&&e.clientHeight){f=e.clientWidth;h=e.clientHeight}else if(b.body){f=b.body.clientWidth;h=b.body.clientHeight}if(h>2*d||f>2*c)return j}return g}function rb(a,b){L(b,function(c,d){a["google_"+d]=c})}
function sb(a,b){if(!b)return a.URL;return a.referrer}function tb(a,b){if(!b&&a.google_referrer_url==i)return"0";else if(b&&a.google_referrer_url==i)return"1";else if(!b&&a.google_referrer_url!=i)return"2";else if(b&&a.google_referrer_url!=i)return"3";return"4"}function ub(a,b,c,d){a.page_url=sb(c,d);a.page_location=i}function vb(a,b,c,d){a.page_url=b.google_page_url;a.page_location=sb(c,d)||"EMPTY"}
function wb(a,b){var c={},d=qb(a,b,a.google_ad_width,a.google_ad_height);c.iframing=tb(a,d);a.google_page_url?vb(c,a,b,d):ub(c,a,b,d);c.last_modified_time=b.URL==c.page_url?Date.parse(b.lastModified)/1E3:i;c.referrer_url=d?a.google_referrer_url:a.google_page_url&&a.google_referrer_url?a.google_referrer_url:b.referrer;return c}function xb(a){var b={},c=a.URL.substring(a.URL.lastIndexOf("http"));b.iframing=i;b.page_url=c;b.page_location=a.URL;b.last_modified_time=i;b.referrer_url=c;return b}
function yb(a,b){b=zb(a,b);rb(a,b)}function zb(a,b){return a=a.google_page_url==i&&Ab[b.domain]?xb(b):wb(a,b)}var Ab={};Ab["ad.yieldmanager.com"]=g;var Bb=function(a,b,c){b=fa(b,l,a);a=window.onerror;window.onerror=b;try{c()}catch(d){c=d.toString();var e="";if(d.fileName)e=d.fileName;var f=-1;if(d.lineNumber)f=d.lineNumber;b=b(c,e,f);if(!b)throw d;}window.onerror=a};q("google_protectAndRun",Bb);
var Db=function(a,b,c,d){if(Math.random()<0.01){var e=Sa;a=["http://",bb,"/pagead/gen_204","?id=jserror","&jscb=",Ta?1:0,"&jscd=",Ua?1:0,"&context=",M(a),"&msg=",M(b),"&file=",M(c),"&line=",M(d.toString()),"&url=",M(e.URL.substring(0,512)),"&ref=",M(e.referrer.substring(0,512))];a.push(Cb());fb(K,a.join(""))}return!Va};q("google_handleError",Db);
var Fb=function(a){Eb|=a},Eb=0,Cb=function(){var a=["&client=",M(K.google_ad_client),"&format=",M(K.google_ad_format),"&slotname=",M(K.google_ad_slot),"&output=",M(K.google_ad_output),"&ad_type=",M(K.google_ad_type)];return a.join("")};var R="",Ib=function(){if(window.google_ad_frameborder==i)window.google_ad_frameborder=0;if(window.google_ad_output==i)window.google_ad_output="html";if(P(window.google_ad_format)){var a=window.google_ad_format.match(/^(\d+)x(\d+)_.*/);if(a){window.google_ad_width=parseInt(a[1],10);window.google_ad_height=parseInt(a[2],10);window.google_ad_output="html"}}window.google_ad_format=Gb(window.google_ad_format,window.google_ad_output,window.google_ad_width,window.google_ad_height,window.google_ad_slot,
!!window.google_override_format);R=window.google_ad_client||"";window.google_ad_client=Hb(window.google_ad_format,window.google_ad_client);yb(window,document);if(window.google_num_slots_by_channel==i)window.google_num_slots_by_channel={};if(window.google_viewed_host_channels==i)window.google_viewed_host_channels={};if(window.google_num_slots_by_client==i)window.google_num_slots_by_client={};if(window.google_prev_ad_formats_by_region==i)window.google_prev_ad_formats_by_region={};if(window.google_prev_ad_slotnames_by_region==
i)window.google_prev_ad_slotnames_by_region={};if(window.google_correlator==i)window.google_correlator=(new Date).getTime();if(window.google_adslot_loaded==i)window.google_adslot_loaded={};if(window.google_adContentsBySlot==i)window.google_adContentsBySlot={};if(window.google_flash_version==i)window.google_flash_version=hb();if(window.google_new_domain_checked==i)window.google_new_domain_checked=0;if(window.google_new_domain_enabled==i)window.google_new_domain_enabled=0;if(!window.google_num_ad_slots)window.google_num_ad_slots=
0;if(!window.google_num_0ad_slots)window.google_num_0ad_slots=0;if(!window.google_num_sdo_slots)window.google_num_sdo_slots=0;window.google_ad_section=window.google_ad_section||window.google_ad_region||"";window.google_country=window.google_country||window.google_gl||"";a=(new Date).getTime();if(o(window.google_color_bg))window.google_color_bg=S(window.google_color_bg,a);if(o(window.google_color_text))window.google_color_text=S(window.google_color_text,a);if(o(window.google_color_link))window.google_color_link=
S(window.google_color_link,a);if(o(window.google_color_url))window.google_color_url=S(window.google_color_url,a);if(o(window.google_color_border))window.google_color_border=S(window.google_color_border,a);if(o(window.google_color_line))window.google_color_line=S(window.google_color_line,a)},Jb=function(a){L(mb,function(b,c){a[c]=i});L(nb,function(b,c){a[c]=i});L(ob,function(b,c){a[c]=i});a.google_container_id=i;a.google_eids=i;a.google_page_location=i;a.google_referrer_url=i;a.google_ad_region=i;
a.google_gl=i},S=function(a,b){Fb(2);return a[b%a.length]},Hb=function(a,b){if(!b)return"";b=b.toLowerCase();return b=P(a)?Kb(b):Lb(b)},Lb=function(a){if(a&&a.substring(0,3)!="ca-")a="ca-"+a;return a},Kb=function(a){if(a&&a.substring(0,7)!="ca-aff-")a="ca-aff-"+a;return a},Gb=function(a,b,c,d,e,f){if(!a&&b=="html")a=c+"x"+d;return a=Mb(a,e,f)?a.toLowerCase():""},Mb=function(a,b,c){if(!a)return j;if(!b)return g;return c};var T=document,U=navigator,V=window;
function Nb(){var a=T.cookie,b=Math.round((new Date).getTime()/1E3),c=V.google_analytics_domain_name;c=typeof c=="undefined"?Ob("auto"):Ob(c);var d=a.indexOf("__utma="+c+".")>-1,e=a.indexOf("__utmb="+c)>-1,f=a.indexOf("__utmc="+c)>-1,h={},n=!!V&&!!V.gaGlobal;if(d){a=a.split("__utma="+c+".")[1].split(";")[0].split(".");h.sid=e&&f?a[3]+"":n&&V.gaGlobal.sid?V.gaGlobal.sid:b+"";h.vid=a[0]+"."+a[1];h.from_cookie=g}else{h.sid=n&&V.gaGlobal.sid?V.gaGlobal.sid:b+"";h.vid=n&&V.gaGlobal.vid?V.gaGlobal.vid:
(Math.round(Math.random()*2147483647)^Pb()&2147483647)+"."+b;h.from_cookie=j}h.dh=c;h.hid=n&&V.gaGlobal.hid?V.gaGlobal.hid:Math.round(Math.random()*2147483647);return V.gaGlobal=h}
function Pb(){var a=T.cookie?T.cookie:"",b=V.history.length,c,d=[U.appName,U.version,U.language?U.language:U.browserLanguage,U.platform,U.userAgent,U.javaEnabled()?1:0].join("");if(V.screen)d+=V.screen.width+"x"+V.screen.height+V.screen.colorDepth;else if(V.java){c=java.awt.Toolkit.getDefaultToolkit().getScreenSize();d+=c.screen.width+"x"+c.screen.height}d+=a;d+=T.referrer?T.referrer:"";for(a=d.length;b>0;)d+=b--^a++;return Qb(d)}
function Qb(a){var b=1,c=0,d;if(!(a==undefined||a=="")){b=0;for(d=a.length-1;d>=0;d--){c=a.charCodeAt(d);b=(b<<6&268435455)+c+(c<<14);c=b&266338304;b=c!=0?b^c>>21:b}}return b}function Ob(a){if(!a||a==""||a=="none")return 1;if("auto"==a){a=T.domain;if("www."==a.substring(0,4))a=a.substring(4,a.length)}return Qb(a.toLowerCase())};var W=function(){this.defaultBucket=[];this.layers={};for(var a=0,b=arguments.length;a<b;++a)this.layers[arguments[a]]=""},Rb=function(a){for(var b=new W,c=0,d=a.defaultBucket.length;c<d;++c)b.defaultBucket.push(a.defaultBucket[c]);L(a.layers,fa(W.prototype.k,b));return b},Sb=function(a){if(!(a&&a.defaultBucket&&a.defaultBucket.push&&a.layers))return j;var b=g,c=function(d,e){if(!(e in a)||typeof d!=typeof a[e])b=j};L(W.prototype,c);return b};W.prototype.k=function(a,b){this.layers[b]=a};
W.prototype.G=function(a,b){if(a=="")return"";if(!b){this.defaultBucket.push(a);return a}if(this.layers.hasOwnProperty(b))return this.layers[b]=a;return""};W.prototype.i=function(a,b,c){if(!c||this.v(c)){var d=Math.random();if(d<b){b=Math.floor(a.length*d/b);if(a=a[b])return this.G(a,c)}}return""};W.prototype.v=function(a){return this.layers.hasOwnProperty(a)&&this.layers[a]==""};W.prototype.a=function(a){if(this.layers.hasOwnProperty(a))return this.layers[a];return""};
W.prototype.u=function(){var a=[],b=function(c){c!=""&&a.push(c)};L(this.layers,b);if(this.defaultBucket.length>0&&a.length>0)return this.defaultBucket.join(",")+","+a.join(",");return this.defaultBucket.join(",")+a.join(",")};var Tb={google:1,googlegroups:1,gmail:1,googlemail:1,googleimages:1,googleprint:1};function Ub(a){a=a.google_page_location||a.google_page_url;if(!a)return j;a=a.toString();if(a.indexOf("http://")==0)a=a.substring(7,a.length);else if(a.indexOf("https://")==0)a=a.substring(8,a.length);var b=a.indexOf("/");if(b==-1)b=a.length;a=a.substring(0,b);a=a.split(".");b=j;if(a.length>=3)b=a[a.length-3]in Tb;if(a.length>=2)b=b||a[a.length-2]in Tb;return b}
var Vb=function(a,b){if(!b)return j;if(b.a("1")=="44901211")return 0==a%2;if(b.a("1")=="44901215")return 0==Math.floor(a/2)%2;if(b.a("1")=="44901216")return 1==Math.floor(a/2)%2;return j};function Wb(a,b,c){if(!Ub(a)&&a.google_new_domain_enabled==1)return Vb(b,c)?"http://"+ab:"http://"+$a;return"http://"+bb};var X=function(a){this.H=a;this.o=[];this.n=0;this.d=[];this.B=0;this.h=[];this.z=j;this.p=this.q="";this.w=j};X.prototype.D=function(a,b){var c=this.H[b],d=this.o;this.H[b]=function(e){if(e&&e.length>0){var f=e.length>1?e[1].url:i;d.push([a,ta(e[0].url),f])}c(e)}};X.prototype.C=function(){this.n++};X.prototype.F=function(a){this.d.push(a)};X.prototype.A=function(){if(!this.z){eb("http://"+Za+"/pagead/osd.js");this.z=g}};
X.prototype.r=function(a){if(this.n>0)for(var b=document.getElementsByTagName("iframe"),c=this.w?"google_ads_iframe_":"google_ads_frame",d=0;d<b.length;d++){var e=b.item(d);e.src&&e.name&&e.name.indexOf(c)==0&&a(e,e.src)}};
X.prototype.s=function(a){var b=this.o;if(b.length>0)for(var c=document.getElementsByTagName("a"),d=0;d<c.length;d++)for(var e=0;e<b.length;e++)if(c.item(d).href==b[e][1]){var f=c.item(d).parentNode;if(b[e][2])for(var h=f,n=0;n<4;n++){if(h.innerHTML.indexOf(b[e][2])>0){f=h;break}h=h.parentNode}a(f,b[e][0]);b.splice(e,1);break}};X.prototype.t=function(a){for(var b=0;b<this.d.length;b++){var c=this.d[b],d=Xb(c);if(d)(d=document.getElementById("google_ads_div_"+d))&&a(d,c)}};
X.prototype.j=function(a){this.s(a);this.t(a);this.r(a)};X.prototype.g=function(a,b,c){this.B=a;this.q=b;this.p=c};X.prototype.c=function(){return this.B};X.prototype.b=function(){return this.q};X.prototype.l=function(){return this.p};X.prototype.m=function(){return this.o.length+this.n+this.d.length};X.prototype.f=function(a){this.h=a};
X.prototype.e=function(a,b,c){if(this.h.length>0){for(var d=0;d<this.h.length;d++)if(this.h[d]==a){this.w=c;if(a=="js")this.D(b,"google_ad_request_done");else if(a=="html")this.C();else a=="json_html"&&this.F(b)}this.A()}};var Xb=function(a){if((a=a.match(/[&\?](?:slotname)=([^&]+)/))&&a.length==2)return a[1];return""},Yb=function(){window.__google_ad_urls||(window.__google_ad_urls=new X(window));return window.__google_ad_urls};q("Goog_AdSense_getAdAdapterInstance",Yb);
q("Goog_AdSense_OsdAdapter",X);q("Goog_AdSense_OsdAdapter.prototype.numBlocks",X.prototype.m);q("Goog_AdSense_OsdAdapter.prototype.findBlocks",X.prototype.j);q("Goog_AdSense_OsdAdapter.prototype.getOsdMode",X.prototype.c);q("Goog_AdSense_OsdAdapter.prototype.getEid",X.prototype.b);q("Goog_AdSense_OsdAdapter.prototype.getCorrelator",X.prototype.l);q("Goog_AdSense_OsdAdapter.prototype.setValidOutputTypes",X.prototype.f);q("Goog_AdSense_OsdAdapter.prototype.setupOsd",X.prototype.g);
q("Goog_AdSense_OsdAdapter.prototype.registerAdBlockByType",X.prototype.e);var Zb=function(a,b){var c=a.nodeType==9?a:a.ownerDocument||a.document;if(c.defaultView&&c.defaultView.getComputedStyle)if(a=c.defaultView.getComputedStyle(a,""))return a[b];return i},$b=function(a,b){return Zb(a,b)||(a.currentStyle?a.currentStyle[b]:i)||a.style[b]},ac=function(a,b,c,d){if(/^\d+px?$/.test(b))return parseInt(b,10);else{var e=a.style[c],f=a.runtimeStyle[c];a.runtimeStyle[c]=a.currentStyle[c];a.style[c]=b;b=a.style[d];a.style[c]=e;a.runtimeStyle[c]=f;return b}},bc=function(a){var b=
a.nodeType==9?a:a.ownerDocument||a.document,c="";if(b.createTextRange){c=b.body.createTextRange();c.moveToElementText(a);c=c.queryCommandValue("FontName")}if(!c){c=$b(a,"fontFamily");if(B&&Ha)c=c.replace(/ \[[^\]]*\]/,"")}a=c.split(",");if(a.length>1)c=a[0];return ua(c,"\"'")},cc=/[^\d]+$/,dc=function(a){return(a=a.match(cc))&&a[0]||i},ec={cm:1,"in":1,mm:1,pc:1,pt:1},fc={em:1,ex:1},gc=function(a){var b=$b(a,"fontSize"),c=dc(b);if(b&&"px"==c)return parseInt(b,10);if(C)if(c in ec)return ac(a,b,"left",
"pixelLeft");else if(a.parentNode&&a.parentNode.nodeType==1&&c in fc){a=a.parentNode;c=$b(a,"fontSize");return ac(a,b==c?"1em":b,"left","pixelLeft")}c=Pa("span",{style:"visibility:hidden;position:absolute;line-height:0;padding:0;margin:0;border:0;height:1em;"});Ra(a,c);b=c.offsetHeight;c&&c.parentNode&&c.parentNode.removeChild(c);return b};var hc,Y={};function ic(a){if(a==1)return g;return!Y[a]}function jc(a,b){if(!(!a||a==""))if(b==1)if(Y[b])Y[b]+=","+a;else Y[b]=a;else Y[b]=a}function kc(){var a=[];L(Y,function(b){a.push(b)});return a.join(",")}function lc(a,b){if(o(a))for(var c=0;c<a.length;c++)p(a[c])&&jc(a[c],b)}var mc=j;function Z(a){return a!=i?'"'+a+'"':'""'}function nc(a){var b="google_unique_id";if(a[b])++a[b];else a[b]=1;return a[b]}
var oc=function(a,b){var c=b.slice(-1),d=c=="?"||c=="#"?"":"&",e=[b];b=function(f,h){if(f||f===0||f===j){if(typeof f=="boolean")f=f?1:0;cb(e,d,h,"=",M(f));d="&"}};L(a,b);return e.join("")};function pc(){var a;if(K.google_ad_output=="html"&&!(O(K)||P(K.google_ad_format))&&ic(0)){a=["6083035","6083034"];a=Q(a,I("0",0));jc(a,0)}return a=="6083035"}
function qc(a,b){if((a.google_unique_id||0)!=0||P(a.google_ad_format))return"";var c="";a=O(a);if(b=="html"||a)c=Q(["36815001","36815002"],I("0.01",0));if(c==""&&(b=="js"||a))c=Q(["36815003","36815004"],I("0.01",0));if(c==""&&(b=="html"||b=="js"))c=Q(["36813005","36813006"],I("0.008",0));return c}
function rc(){var a=Yb(),b=window.google_enable_osd,c;if(b===g){c="36813006";sc(c,a)}else if(b!==j&&ic(0)){c=a.b();if(c=="")(c=qc(window,window.google_ad_output))&&sc(c,a);else if(c!="36815001"&&c!="36815002"&&c!="36815003"&&c!="36815004"&&c!="36813005"&&c!="36813006")c=""}if(c){jc(c,0);return c}return""}
function sc(a,b){var c=b.c(),d=[];switch(a){case "36815004":c=1;d=["js"];break;case "36815002":c=1;d=["html"];break;case "36813006":c=0;d=["html","js"];break}d.length>0&&b.f(d);b.g(c,a,window.google_correlator)}
function tc(a,b,c,d){var e=nc(a);c=oc({ifi:e},c);c=c.substring(0,1992);c=c.replace(/%\w?$/,"");var f="script";if((a.google_ad_output=="js"||a.google_ad_output=="json_html")&&(a.google_ad_request_done||a.google_radlink_request_done))b.write("<"+f+' language="JavaScript1.1" src='+Z(k(c))+"></"+f+">");else if(a.google_ad_output=="html")if(mc&&(typeof ExpandableAdSlotFactory=="function"||typeof ExpandableAdSlotFactory=="object")&&typeof ExpandableAdSlotFactory.createIframe=="function"){b=a.google_container_id||
d||i;a["google_expandable_ad_slot"+e]=ExpandableAdSlotFactory.createIframe("google_ads_frame"+e,k(c),a.google_ad_width,a.google_ad_height,b)}else{e='<iframe name="google_ads_frame" width='+Z(a.google_ad_width)+" height="+Z(a.google_ad_height)+" frameborder="+Z(a.google_ad_frameborder)+" src="+Z(k(c))+' marginwidth="0" marginheight="0" vspace="0" hspace="0" allowtransparency="true" scrolling="no"></iframe>';a.google_container_id?uc(a.google_container_id,b,e):b.write(e)}return c}
function vc(a){Jb(a)}function wc(a){var b=xc().a("ac1")=="44901217";if(!yc(b))return j;b=pc();var c=Wb(window,window.google_unique_id||0,xc());a=zc(a);b=c+Ac(a.google_ad_format,b);window.google_ad_url=oc(a,b);return g}
var Dc=function(a){a.dt=aa;var b=window.google_prev_ad_formats_by_region,c=window.google_ad_section,d=window.google_ad_format,e=window.google_ad_slot;if(b[c])if(!P(d)){a.prev_fmts=b[c];if(window.google_num_slots_by_client.length>1)a.slot=window.google_num_slots_by_client[R]}var f=window.google_prev_ad_slotnames_by_region;if(f[c])a.prev_slotnames=f[c].toLowerCase();if(d){if(!P(d))if(b[c])b[c]+=","+d;else b[c]=d}else if(e)if(f[c])f[c]+=","+e;else f[c]=e;a.correlator=window.google_correlator;if(window.google_new_domain_checked==
1&&window.google_new_domain_enabled==0)a.dblk=1;if(window.google_ad_channel){b=window.google_num_slots_by_channel;c="";d=window.google_ad_channel.split(Bc);for(e=0;e<d.length;e++){f=d[e];if(b[f])c+=f+"+";else b[f]=1}a.pv_ch=c}if(window.google_ad_host_channel){b=Cc(window.google_ad_host_channel,window.google_viewed_host_channels);a.pv_h_ch=b}if(Ta)a.jscb=1;if(Ua)a.jscd=1;a.frm=window.google_iframing;b=Nb();a.ga_vid=b.vid;a.ga_sid=b.sid;a.ga_hid=b.hid;a.ga_fc=b.from_cookie;a.ga_wpids=window.google_analytics_uacct},
Ec=function(a){var b=g;if(b=jb(b)){a.biw=b.width;a.bih=b.height}},Fc=function(a){var b=lb(window);if(b!=0)a.ifk=b.toString()};function Cc(a,b){var c=a.split("|");a=-1;for(var d=[],e=0;e<c.length;e++){var f=c[e].split(Bc);b[e]||(b[e]={});for(var h="",n=0;n<f.length;n++){var x=f[n];if(x!="")if(b[e][x])h+="+"+x;else b[e][x]=1}h=h.slice(1);d[e]=h;if(h!="")a=e}b="";if(a>-1){for(e=0;e<a;e++)b+=d[e]+"|";b+=d[a]}return b}
var $=function(){if(window.google_exp_persistent&&Sb(window.google_exp_persistent))return window.google_exp_persistent;return new W("1","ac1")};q("google_exp_persistent",$());var xc=function(){hc||(hc=Rb($()));return hc};function Gc(){var a=["44901211","44901215","44901216","44901212"];$().i(a,I("0.0001",0),"1");a=["44901217","44901218"];$().i(a,I("0",0),"ac1")}
function Hc(){0==(window.google_unique_id||0)&&Gc();var a=rc(),b=Math.random()<0.01,c=i,d="";if(b){d="google_temp_span";c=Ic(d)}b=wc(c);c&&c.id==d&&(c&&c.parentNode?c.parentNode.removeChild(c):i);if(b){c=tc(window,document,window.google_ad_url);a&&Yb().e(window.google_ad_output,c,j);vc(window)}}
var Jc=function(a){L(nb,function(b,c){a[b]=window[c]});L(mb,function(b,c){a[b]=window[c]});L(ob,function(b,c){a[b]=window[c]})},Kc=function(a){lc(window.google_eids,1);a.eid=kc();var b=xc().u();if(a.eid.length>0&&b.length>0)a.eid+=",";a.eid+=b};function Lc(){Ib()}
function Mc(a){var b={};a=a.split("?");a=a[a.length-1].split("&");for(var c=0;c<a.length;c++){var d=a[c].split("=");if(d[0])try{b[d[0].toLowerCase()]=d.length>1?window.decodeURIComponent?decodeURIComponent(d[1].replace(/\+/g," ")):unescape(d[1]):""}catch(e){}}return b}function Nc(){var a=window,b=Mc(document.URL);if(b.google_ad_override){a.google_ad_override=b.google_ad_override;a.google_adtest="on"}}
function uc(a,b,c){if(a)if((a=b.getElementById(a))&&c&&c.length!=""){a.style.visibility="visible";a.innerHTML=c}}
var Ac=function(a,b){return a=P(a)?"/pagead/sdo?":b?"/pagead/render_iframe_ads.html#":"/pagead/ads?"},Oc=function(a,b){b.dff=bc(a);b.dfs=gc(a)},Pc=function(a){a.ref=window.google_referrer_url;a.loc=window.google_page_location},yc=function(a){var b=window.google_prev_ad_formats_by_region,c=window.google_prev_ad_slotnames_by_region,d=window.google_ad_section;if(P(window.google_ad_format)){window.google_num_sdo_slots+=1;if(!a&&window.google_num_sdo_slots>4)return j}else if(O(window)){window.google_num_0ad_slots+=
1;if(!a&&window.google_num_0ad_slots>3)return j}else{window.google_num_ad_slots+=1;if(window.google_num_slots_to_rotate){Fb(1);b[d]=i;c[d]=i;if(window.google_num_slot_to_show==i)window.google_num_slot_to_show=(new Date).getTime()%window.google_num_slots_to_rotate+1;if(window.google_num_slot_to_show!=window.google_num_ad_slots)return j}else if(!a&&window.google_num_ad_slots>6&&d=="")return j}a=window.google_num_slots_by_client;if(a[R])a[R]+=1;else{a[R]=1;a.length+=1}return g},zc=function(a){var b=
{};Jc(b);Dc(b);ib(b);a&&Oc(a,b);Ec(b);Fc(b);Kc(b);Pc(b);b.fu=Eb;return b},Ic=function(a){var b=window.google_container_id&&H(window.google_container_id)||H(a);if(!b&&!window.google_container_id&&a){document.write("<span id="+a+"></span>");b=H(a)}return b},Bc=/[+, ]/;window.google_render_ad=Hc;function Qc(){var a=[],b=Rc();if(b)if(b=b.getSlots())for(var c=0,d=b.length;c<d;c++){var e=Sc(b[c]);a.push(e)}return a}q("googleGetCompanionAdSlots",Qc);function Sc(a){var b={};if(a){b.slotId=a.getSlotId().getId();b.adType=a.get("ad_type");b.adSizes=Tc(a.getSizes())}return b}function Tc(a){var b=[];if(a&&o(a))for(var c=0,d=a.length;c<d;c++){var e={};e.adHeight=a[c].getHeight();e.adWidth=a[c].getWidth();b.push(e)}return b}
function Uc(a){var b=Rc();if(b&&a&&o(a)){var c=b.getSlotIdMap();if(c)for(var d=0,e=a.length;d<e;d++){var f=a[d],h=f.slotId;(f=f.adContent)&&h in c&&b.fillSlot(c[h],f)}}}q("googleSetCompanionAdContents",Uc);function Rc(){if(typeof googletag!="undefined"&&googletag&&typeof googletag.companionAds=="function")return googletag.companionAds();return i}
function Vc(a){var b=window,c=document;if(b.google_container_id)if(a){b=c.getElementById(b.google_container_id);b.innerHTML=a;b.style.visibility="visible"}else Hc()}q("google_show_companion_ad",Vc);function Wc(a,b){if(a&&b){a=document.getElementById(a);a.innerHTML=b;a.style.visibility="visible"}}q("google_show_companion_ad_in_slot",Wc);
function Xc(){var a={},b=window;if(b.google_container_id){a.adType=b.google_ad_type;a.adHeight=b.google_ad_height;a.adWidth=b.google_ad_width;a.adContainerId=b.google_container_id}return a}q("google_get_companion_slot_params",Xc);function Yc(){Nc();Lc()}Bb("show_companion_ads.main",Db,Yc);})()


}
/*
     FILE ARCHIVED ON 03:14:10 Feb 12, 2010 AND RETRIEVED FROM THE
     INTERNET ARCHIVE ON 07:01:53 Dec 16, 2024.
     JAVASCRIPT APPENDED BY WAYBACK MACHINE, COPYRIGHT INTERNET ARCHIVE.

     ALL OTHER CONTENT MAY ALSO BE PROTECTED BY COPYRIGHT (17 U.S.C.
     SECTION 108(a)(3)).
*/
/*
playback timings (ms):
  captures_list: 0.686
  exclusion.robots: 0.022
  exclusion.robots.policy: 0.009
  esindex: 0.014
  cdx.remote: 49.093
  LoadShardBlock: 126.733 (6)
  PetaboxLoader3.datanode: 235.285 (8)
  load_resource: 285.407 (2)
  PetaboxLoader3.resolve: 156.271 (2)
*/